# Generated by Django 5.2.5 on 2025-10-16 09:20

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_image', models.ImageField(blank=True, null=True, upload_to='artworks/finals/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('lineart', 'Лайнарт'), ('flat_colors', 'Плоские цвета'), ('sketch', 'Скетч'), ('basic_render', 'Базовый рендер'), ('premium_render', 'Премиальный рендер')], max_length=50)),
                ('purpose', models.CharField(choices=[('commission', 'Заказ'), ('promo', 'Промоматериалы'), ('collab', 'Коллаборация')], default='commission', max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=50)),
                ('expected_completion_date', models.DateField(blank=True, null=True)),
                ('actual_completion_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('RUB', 'RUB'), ('EUR', 'EUR'), ('KZT', 'KZT')], default='USD', max_length=3)),
                ('accepted_at', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True, max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='PriceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pricelist/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='refs/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('kind', models.CharField(choices=[('ref', 'Референс'), ('pose', 'Поза'), ('color', 'Цвет/палитра'), ('mood', 'Мудборд'), ('other', 'Другое')], default='ref', max_length=16)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('source_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
