# Generated by Django 5.2.5 on 2025-10-16 09:20

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commissioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('paypal_email', models.EmailField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('artist', '🎨 Artist'), ('manager', '📋 Manager'), ('middleman', '💸 Middleman'), ('client', '🧍 Client'), ('admin', '🛠 Admin')], default='client', max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='as_manager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='as_artist', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artists', to='identity.manager', verbose_name='Менеджер')),
            ],
        ),
        migrations.CreateModel(
            name='Middleman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('paypal_address', models.CharField(max_length=70)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='middleman_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArtistContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media', models.CharField(choices=[('telegram', 'Telegram'), ('discord', 'Discord'), ('twitter', 'Twitter (X)'), ('bluesky', 'Bluesky'), ('instagram', 'Instagram'), ('email', 'Email'), ('other', 'Другое')], max_length=50, verbose_name='Соцсеть')),
                ('handle', models.CharField(help_text='Ник, @handle, email или иное представление', max_length=255, verbose_name='Адрес/идентификатор')),
                ('url', models.URLField(blank=True, validators=[django.core.validators.URLValidator()], verbose_name='Ссылка')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='identity.artist', verbose_name='Художник')),
            ],
            options={
                'verbose_name': 'Контакт художника',
                'verbose_name_plural': 'Контакты художника',
                'indexes': [models.Index(fields=['artist', 'social_media'], name='identity_ar_artist__3fa638_idx')],
                'constraints': [models.UniqueConstraint(fields=('artist', 'social_media', 'handle'), name='uniq_artist_contact')],
            },
        ),
        migrations.CreateModel(
            name='CommissionerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media', models.CharField(choices=[('telegram', 'Telegram'), ('discord', 'Discord'), ('twitter', 'Twitter (X)'), ('bluesky', 'Bluesky'), ('instagram', 'Instagram'), ('email', 'Email'), ('other', 'Другое')], max_length=50, verbose_name='Соцсеть')),
                ('handle', models.CharField(help_text='Ник/идентификатор, можно с @', max_length=255)),
                ('url', models.URLField(blank=True, max_length=500, validators=[django.core.validators.URLValidator()])),
                ('commissioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='identity.commissioner')),
            ],
            options={
                'verbose_name': 'Контакт/соцсеть',
                'verbose_name_plural': 'Контакты/соцсети',
                'indexes': [models.Index(fields=['commissioner', 'social_media'], name='identity_co_commiss_3da31a_idx')],
                'constraints': [models.UniqueConstraint(fields=('commissioner', 'social_media', 'handle'), name='uniq_comm_contact')],
            },
        ),
    ]
