# Generated by Django 5.2.5 on 2025-10-16 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ('user__username',)},
        ),
    ]
