# Generated by Django 5.2.5 on 2025-10-16 09:20

import django.db.models.deletion
import django.utils.timezone
import recurrence.fields
import schedule.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulePattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('days_off_at_start', models.PositiveSmallIntegerField(default=0)),
                ('pattern_after_start', models.JSONField(default=list)),
                ('last_day_always_working', models.BooleanField(default=False)),
                ('working_day_duration', models.PositiveSmallIntegerField(default=4)),
            ],
            options={
                'verbose_name_plural': 'Шаблоны расписания',
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_range', models.DateTimeField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('event', 'Событие'), ('task', 'Задача')], default='event', max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('recurrence', recurrence.fields.RecurrenceField(blank=True, null=True)),
                ('start_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('incomplete', 'INCOMPLETE'), ('complete', 'COMPLETE'), ('cancelled', 'CANCELLED'), ('on_pause', 'ON_PAUSE'), ('in_process', 'IN_PROCESS')], default='incomplete', max_length=50)),
                ('is_balance_correction', models.BooleanField(default=False)),
                ('date_day', models.DateField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('work', 'Рабочее'), ('life', 'Пожизневые'), ('sport', 'Спорт'), ('medical', 'Медицина')], max_length=32, null=True)),
                ('type', models.CharField(blank=True, choices=[('fun', 'Кайфовые'), ('routine', 'Рутина'), ('important', 'Важные'), ('heavy', 'Трудоемкие'), ('gross', 'Мерзкие')], max_length=32, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='accounting.account')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Событие или задача',
                'verbose_name_plural': 'События и задачи',
            },
        ),
        migrations.CreateModel(
            name='EventInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('incomplete', 'INCOMPLETE'), ('complete', 'COMPLETE'), ('cancelled', 'CANCELLED'), ('on_pause', 'ON_PAUSE'), ('in_process', 'IN_PROCESS')], default='incomplete', max_length=50)),
                ('is_completed', models.BooleanField(default=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('parent_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='schedule.event')),
            ],
        ),
        migrations.CreateModel(
            name='MonthSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=schedule.models.current_year)),
                ('month', models.PositiveSmallIntegerField(default=schedule.models.current_month)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedule.schedulepattern')),
            ],
            options={
                'verbose_name_plural': 'Расписания на месяц',
                'unique_together': {('user', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='DayOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('work', 'Рабочий'), ('off', 'Выходной'), ('holiday', 'Праздник'), ('vacation', 'Отпуск'), ('task', 'Дело')], default='off', max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('month_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='schedule.monthschedule')),
            ],
            options={
                'verbose_name_plural': 'Исключения расписания',
                'constraints': [models.UniqueConstraint(fields=('month_schedule', 'date'), name='unique_day_per_monthschedule')],
            },
        ),
    ]
