# Generated by Django 5.2.5 on 2025-10-17 15:36

import django.db.models.deletion
import schedule.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_event_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulepattern',
            name='mode',
            field=models.CharField(choices=[('alternating', 'Чередование блоков'), ('weekday', 'По дням недели')], default='alternating', max_length=20),
        ),
        migrations.AddField(
            model_name='schedulepattern',
            name='weekday_map',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='monthschedule',
            name='pattern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='month_schedules', to='schedule.schedulepattern'),
        ),
        migrations.AlterField(
            model_name='schedulepattern',
            name='working_day_duration',
            field=models.DecimalField(decimal_places=2, default=Decimal('4.00'), max_digits=4, validators=[schedule.models.validate_quarter_hours]),
        ),
        migrations.AddConstraint(
            model_name='monthschedule',
            constraint=models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='month_between_1_and_12'),
        ),
    ]
