# Generated by Django 5.2.5 on 2025-10-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_schedulepattern_mode_schedulepattern_weekday_map_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_mode',
            field=models.CharField(choices=[('exact_date', 'Точная дата'), ('number_of_month', 'нормер месяца'), ('number_of_week', 'N-я неделя')], default='exact_date', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='is_recurring_monthly',
            field=models.BooleanField(default=False, help_text='True — повторяемое по месяцам (интервал в месяцах, старт/финиш берём из start_datetime/end_datetime).'),
        ),
        migrations.AddField(
            model_name='event',
            name='month_interval',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Интервал в месяцах (1..12) для повторяемого MONTH-режима.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='month_number',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Месяц (1-12) для режима NUMBER_OF_MONTH.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='month_year',
            field=models.PositiveIntegerField(blank=True, help_text='Год для режима NUMBER_OF_MONTH (например, 2025).', null=True),
        ),
    ]
