# Generated by Django 5.2.5 on 2025-12-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_event_date_mode_event_is_recurring_monthly_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_mode',
            field=models.CharField(blank=True, choices=[('exact_date', 'Точная дата'), ('number_of_month', 'нормер месяца'), ('number_of_week', 'N-я неделя')], default='exact_date', max_length=20),
        ),
    ]
