# Generated by Django 5.2.5 on 2025-10-16 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('artworks', '0001_initial'),
        ('identity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financialentry',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_entries', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='financialentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='middleman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='identity.middleman'),
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='artworks.commission'),
        ),
        migrations.AddField(
            model_name='payout',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='identity.artist'),
        ),
        migrations.AddField(
            model_name='payout',
            name='middleman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity.middleman'),
        ),
        migrations.AddField(
            model_name='payout',
            name='orders',
            field=models.ManyToManyField(to='artworks.artwork'),
        ),
        migrations.AddField(
            model_name='payout',
            name='payments',
            field=models.ManyToManyField(to='accounting.payment'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['user', 'is_primary'], name='accounting__user_id_3a90fa_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['user', 'name'], name='accounting__user_id_f900e0_idx'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('user',), name='unique_primary_account_per_user'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_account_name_per_user'),
        ),
        migrations.AddIndex(
            model_name='financialentry',
            index=models.Index(fields=['user', 'year', 'month'], name='accounting__user_id_faa683_idx'),
        ),
        migrations.AddIndex(
            model_name='financialentry',
            index=models.Index(fields=['account', 'year', 'month'], name='accounting__account_db8537_idx'),
        ),
        migrations.AddConstraint(
            model_name='financialentry',
            constraint=models.UniqueConstraint(fields=('user', 'account', 'year', 'month', 'entry_type', 'currency'), name='uniq_fin_entry_bucket'),
        ),
    ]
