# Generated by Django 5.2.5 on 2025-12-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('RUB', 'RUB'), ('EUR', 'EUR'), ('KZT', 'KZT')], default='RUB', max_length=3),
            preserve_default=False,
        ),
    ]
